name: Deploy Next.js to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: Pc7ESlpogynSmi3OOZit8g02
          vercel-org-id: 2WwUXokENzZvtrhmYU6UEgAZ
          vercel-project-id: prj_1D7rvVdq2GQMoFOEwxaQJ1TsQcRv
          vercel-args: '--prod'
